name = "music downloader PM"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"

  [[processes.tasks]]
  id = "f1e2rk58q4vbhkazq95o5b69"
  title = "find a way to load streaming from the spotify API"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = "Low"
  linkCommits = [ ]

[[processes]]
id = "process2"
name = "In Progress"

  [[processes.tasks]]
  id = "thkjnadh8qoxuhzcekbfol5q"
  title = "implement a jester"
  description = "I have no idea what to test lmao"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "vrjw8iu5em37n1ue9tac5yth"
  title = "Fix login bug"
  description = """
TL;DR

Seems I have to use an authorization token, which for my app i have not been using. This is important because other users that are not me won't be able to use the app, which kinda beats the purpose. """
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process3"
name = "Done"

  [[processes.tasks]]
  id = "task1"
  title = "Browser auto-opens when running login server"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "nnctbcemmxpjyura3icwpedb"
  title = "Browser closes after getting to /login and into the callback"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "molah9w8d6lm079waw5csnte"
  title = "Fix music prompt after login"
  description = "<p></p>"
  tag = "bug"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "j3872mf9gwyifyk09wyyj84z"
  title = "Remove progressbar, use default"
  description = ""
  tag = "cli"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = "Low"
  linkCommits = [ ]

  [[processes.tasks]]
  id = "wvxa5wvg9tf5szf9sgwhuiys"
  title = "Allow Spotituby plz"
  description = '<p>Agree</p><p> Tell puppeteer to look at this button and do something about it</p><p></p><p>Use this</p><p></p><p>&lt;button data-testid="auth-accept" data-encore-id="buttonPrimary" class="Button-sc-qlcn5g-0 hVnPpH"&gt;&lt;span class="ButtonInner-sc-14ud5tc-0 dOeYIb encore-bright-accent-set"&gt;&lt;p data-encore-id="type" class="Type__TypeElement-sc-goli3j-0 bkjCej"&gt;Agree&lt;/p&gt;&lt;/span&gt;&lt;span class="ButtonFocus-sc-2hq6ey-0 iMcXKe"&gt;&lt;/span&gt;&lt;/button&gt;</p>'
  tag = "bug"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = "High"
  linkCommits = [ ]

  [[processes.tasks]]
  id = "lvpws0ingpg1i6akfsp3x69h"
  title = "Modify mp3 metadata with spotify data"
  description = ""
  tag = "cli"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = "High"
  linkCommits = [ ]

  [[processes.tasks]]
  id = "v1lpyqddavsj7twc1m5swhnc"
  title = "Get a public playlist"
  description = "Returns a public playlist given a spotify playlist url"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "da4ysp6vwjj8jcq7jr7e94a2"
name = "Scrapped"

  [[processes.tasks]]
  id = "gsx1xsxt4ri5etnhdi9hz4a7"
  title = "Get All playlists using server"
  description = "Get playlists from the user"
  tag = "backend"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "llv5r9dmvk8pz34ekwnfsup1"
  title = "Implement basic user info"
  description = "<p></p>"
  tag = "backend"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]
